"""Codes de raison stables (§55) et codes de risque."""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    EDGE_BELOW_COSTS = "EDGE_BELOW_COSTS"
    UNCERTAINTY_TOO_HIGH = "UNCERTAINTY_TOO_HIGH"
    DATA_STALE = "DATA_STALE"
    BOOK_INVALID = "BOOK_INVALID"
    RISK_LIMIT = "RISK_LIMIT"
    TURNOVER_NOT_JUSTIFIED = "TURNOVER_NOT_JUSTIFIED"
    UNIVERSE_INSUFFICIENT = "UNIVERSE_INSUFFICIENT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    JEV_FALLBACK = "JEV_FALLBACK"
    ORDER_STATE_UNKNOWN = "ORDER_STATE_UNKNOWN"
    NO_VALID_TARGET = "NO_VALID_TARGET"
    # Raisons complémentaires (risque, exploitation)
    HALTED = "HALTED"
    NOT_LEADER = "NOT_LEADER"
    RECONCILIATION_PENDING = "RECONCILIATION_PENDING"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    PAYLOAD_HASH_MISMATCH = "PAYLOAD_HASH_MISMATCH"
    MARGIN_INSUFFICIENT = "MARGIN_INSUFFICIENT"
    LIQUIDITY_INSUFFICIENT = "LIQUIDITY_INSUFFICIENT"
    CLOCK_DRIFT = "CLOCK_DRIFT"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    DRAWDOWN_REVIEW = "DRAWDOWN_REVIEW"
    INSTRUMENT_NOT_TRADABLE = "INSTRUMENT_NOT_TRADABLE"
    UNIVERSE_EXIT_REDUCE_ONLY = "UNIVERSE_EXIT_REDUCE_ONLY"
    DECISION_SKIPPED_OVERLAP = "DECISION_SKIPPED_OVERLAP"
    SNAPSHOT_EXPIRED = "SNAPSHOT_EXPIRED"
    OK = "OK"
